#include "matches.h"
#include<iostream>
#include<stdlib.h>

using namespace std;
void matches::match()
{
    system("cls");
    cout<<"Saturday, April 7: Match 1- Mumbai Indians vs Chennai Super Kings, 20:00 IST, Wankhede Stadium, Mumbai\n\nSunday, April 8: Match 2- Delhi Daredevils v Kings XI Punjab, 16:00 IST, Feroz Shah Kotla Ground, Delhi\n                  Match 3 - Kolkata Knight Riders v Royal Challengers Bangalore, 20:00 IST, Eden Gardens, Kolkata\n\nMonday, April 9: Match 4- Sunrisers Hyderabad v Rajasthan Royals, 20:00 IST, Rajiv Gandhi Intl. Cricket Stadium, Hyderabad\n\nTuesday, April 10: Match 5- Chennai Super Kings v Kolkata Knight Riders, 20:00 IST, MA Chidambaram Stadium, Chennai\n\nWednesday, April 11: Match 6- Rajasthan Royals v Delhi Daredevils, 20:00 IST, Sawai Mansingh Stadium, Jaipur\n\nThursday, April 12: Match 7- Sunrisers Hyderabad v Mumbai Indians, 20:00 IST, Rajiv Gandhi Intl. Cricket Stadium, Hyderabad\n\nFriday, April 13: Match 8- Royal Challengers Bangalore v Kings XI Punjab, 20:00 IST, M. Chinnaswamy Stadium, Bengaluru\n\nSaturday, April 14: Match 9- Mumbai Indians v Delhi Daredevils, 16:00 IST, Wankhede Stadium, Mumbai\n                      Match 10- Kolkata Knight Riders v Sunrisers Hyderabad, 20:00 IST, Eden Gardens, Kolkata\n\nSunday, April 15: Match 11- Royal Challengers Bangalore v Rajasthan Royal, 16:00 IST, M. Chinnaswamy Stadium, Bengaluru\n                  Match 12- Kings XI Punjab v Chennai Super Kings, 20:00 IST, Holkar Cricket Stadium, Indore\n\nMonday, April 16: Match 13- Kolkata Knight Riders v Delhi Daredevils, 20:00 IST, Eden Gardens, Kolkata\n\nTuesday, April 17: Match 14- Mumbai Indians v Royal Challengers Bangalore, 20:00 IST, Wankhede Stadium, Mumbai\n\nWednesday, April 18: Match 15- Rajasthan Royals v Kolkata Knight Riders, 20:00 IST, Sawai Mansingh Stadium, Jaipur\n\nThursday, April 19: Match 16- Kings XI Punjab v Sunrisers Hyderabad, 20:00 IST, Holkar Cricket Stadium, Indore\n\nFriday, April 20: Match 17- Chennai Super Kings v Rajasthan Royals, 20:00 IST, MA Chidambaram Stadium, Chennai\n\nSaturday, 21st April: Match 18- Kolkata Knight Riders v Kings XI Punjab, 16:00 IST, Eden Gardens, Kolkata\n                  Match 19- Delhi Daredevils v Royal Challengers Bangalore, 20:00 IST, Feroz Shah Kotla Ground, Delhi\n\n                  "
    " Match 21- Rajasthan Royals v Mumbai Indians, 20:00 IST, Sawai Mansingh Stadium, Jaipur\n\nMonday, April 23: Match 22- Kings XI Punjab v Delhi Daredevils, 20:00 IST, Holkar Cricket Stadium, Indore\n\nTuesday, April 24, Match 23- Mumbai Indians v Sunrisers Hyderabad, 20:00 IST, Wankhede Stadium, Mumbai\n\nWednesday, April 25: Match 24- Royal Challengers Bangalore v Chennai Super Kings, 20:00 IST, M. Chinnaswamy Stadium, Bengaluru\n\nThursday, April 26: Match 25- Sunrisers Hyderabad v Kings XI Punjab, 20:00 IST, Rajiv Gandhi Intl. Cricket Stadium, Hyderabad\n\nFriday, April 27: Match 26- Delhi Daredevils v Kolkata Knight Riders, 20:00 IST, Feroz Shah Kotla Ground, Delhi\n\nSaturday, April 28: Match 27- Chennai Super Kings v Mumbai Indians, 20:00 IST, M. A. Chidambaram Stadium, Chennai\n\nSunday, April 29: Match 28- Rajasthan Royals v Sunrisers Hyderabad, 16:00 IST, Sawai Mansingh Stadium, Jaipur\n                    Match 29- Royal Challengers Bangalore v Kolkata Knight Riders, 20:00 IST, M. Chinnaswamy Stadium, Bengaluru\n\nMonday, April 30: Match 30: Chennai Super Kings v Delhi Daredevils, 20:00 IST, M. A. Chidambaram Stadium, Chennai\n\nTuesday, May 1: Match 31- Royal Challengers Bangalore v Mumbai Indians, 20:00 IST, M. Chinnaswamy Stadium, Bengaluru\n\nWednesday, May 2: Match 32- Delhi Daredevils v Rajasthan Royals, 20:00 IST, Feroz Shah Kotla Ground, Delhi\n\nThursday, May 3: Match 33- Kolkata Knight Riders v Chennai Super Kings, 20:00 IST, Eden Gardens, Kolkata\n\nFriday, May 4, Match 34- Kings XI Punjab v Mumbai Indians, 20:00 IST, IS Bindra Stadium, Mohali\n\nSaturday, May 5, Match 35- Chennai Super Kings v Royal Challengers Bangalore, 16:00 IST, M. A. Chidambaram Stadium, Chennai\n                   Match 36- Sunrisers Hyderabad v Delhi Daredevils, 20:00 IST, Rajiv Gandhi Intl. Cricket Stadium, Hyderabad\n\nSunday, May 6, Match 37- Mumbai Indians v Kolkata Knight Riders, 16:00 IST, Wankhede Stadium, Mumbai\n                     Match 38- Kings XI Punjab v Rajasthan Royals, 20:00 IST, IS Bindra Stadium, Mohali\n\nMonday, May 7, Match 39- Sunrisers Hyderabad v Royal Challengers Bangalore, 20:00 IST, Rajiv Gandhi Intl. Cricket Stadium, Hyderabad\n\nTuesday, May 8, Match 40- Rajasthan Royals v Kings XI Punjab, 20:00 IST, Sawai Mansingh Stadium, Jaipur\n\nWednesday, May 9, Match 41- Kolkata Knight Riders v Mumbai Indians, 20:00 IST, Eden Gardens, Kolkata\n\n"
    "Thursday, May 10, Match 42- Delhi Daredevils v Sunrisers Hyderabad, 20:00 IST, Feroz Shah Kotla Ground, Delhi\n\nFriday, May 11, Match 43- Rajasthan Royals v Chennai Super Kings, 20:00 IST, Sawai Mansingh Stadium, Jaipur\n\nSaturday, May 12, Match 44- Kings XI Punjab v Kolkata Knight Riders, 16:00 IST, IS Bindra Stadium, Mohali\n                  Match 45- Royal Challengers Bangalore v Delhi Daredevils, 20:00 IST, M. Chinnaswamy Stadium, Bengaluru\n\nSunday, May 13, Match 46- Chennai Super Kings v Sunrisers Hyderabad, 16:00 IST, M. A. Chidambaram Stadium, Chennai\n                   Match 47- Mumbai Indians v Rajasthan Royals, 20:00 IST, Wankhede Stadium, Mumbai\n\nMonday, May 14, Match 48- Kings XI Punjab v Royal Challengers Bangalore, 20:00 IST, IS Bindra Stadium, Mohali\n\nTuesday, May 15, Match 49- Kolkata Knight Riders v Rajasthan Royals, 20:00 IST, Eden Gardens, Kolkata\n\nWednesday, May 16, Match 50- Mumbai Indians v Kings XI Punjab, 20:00 IST, Wankhede Stadium, Mumbai\n\nThursday, May 17, Match 51- Royal Challengers Bangalore v Sunrisers Hyderabad, 20:00 IST, M. Chinnaswamy Stadium, Bengaluru\n\nFriday, May 18, Match 52- Delhi Daredevils v Chennai Super Kings, 20:00 IST, Feroz Shah Kotla Ground, Delhi\n\nSaturday, May 19, Match 53- Rajasthan Royals v Royal Challengers Bangalore, 16:00 IST, Sawai Mansingh Stadium, Jaipur\n                  Match 54- Sunrisers Hyderabad v Kolkata Knight Riders, 20:00 IST, Rajiv Gandhi Intl. Cricket Stadium, Hyderabad\n\nSunday, May 20, Match 55- Delhi Daredevils v Mumbai Indians, 16:00 IST, Feroz Shah Kotla Ground, Delhi\n                  Match 56- Chennai Super Kings v Kings XI Punjab, 20:00 IST, MA Chidambaram Stadium, Chennai\n\nTuesday, May 22: TBC v TBC, Qualifier 1, 20:00 IST (14:30 GMT), Wankhede Stadium, Mumbai\n\nWednesday, May 23: TBC v TBC Eliminator, 20:00 IST (14:30 GMT), TBC, TBC\n\nFriday, May 25: TBC v TBC, Qualifier 2, 20:00 IST (14:30 GMT), TBC, TBC\n\nSunday, May 27: TBC v TBC, Final, 20:00 IST (14:30 GMT), Wankhede Stadium, Mumbai\n";

}
